### ISSUE TITLE
Support JWT as an alternative REST token implementation

### ISSUE THREAD

**Issue by hhamalai** [Tivix/django-rest-auth#122]
e.g. https://github.com/GetBlimp/django-rest-framework-jwt already integrates with Django rest framework.

**Comment by jgr3go** [comment]
I have a fork mostly ready with JWT support (instead of Token based authentication).
https://github.com/Tivix/django-rest-auth/compare/master...jgr3go:jwt-support?expand=1

Currently, this reads a new setting: `REST_USE_JWT`, and if `True` will attempt to encode the responses for Login, Register, and SocialLogin with `django-rest-framework-jwt`'s default response:  

    { 'user': ...,
      'token': <jwt-token> }

This still probably needs some documentation updates, but before submitting the pull request I'd like feedback on:

1) Whether anyone disagrees with this approach and 
2) Whether anyone sees an issues with how it's been implemented.  All of the tests pass, and when I drop it into my JWT based application it works, but I don't know a lot about DRF's token based authentication so want to make sure I'm not going to be breaking anything.

**Comment by jgr3go** [comment]
On second thought I just created pull #147 because it makes more sense to discuss it inline with the code.
