### ISSUE TITLE
Unable to import serializer

### ISSUE THREAD

**Issue by Drachenfels** [Tivix/django-rest-auth#266]
Running following code:

`python -c 'from rest_auth.serializers import LoginSerializer'`

kill's the program. Is that to be expected?

This causes program to do ka-boom in any context except django app running (tests, sphinx, shell programs) as soon as we put mentioned above import anywhere in our program (and we do that to extend LoginSerializer).

Solution for us is to move LoginSerializer extension to separate file, right now it's grouped with other serializers that are imported by views. However if all of that is to be expected I guess documentation should contain a line or two that if you have an error "Models aren't loaded yet" you should make sure that rest_auth.serializer is not imported in context of views and/or models.

That being said I believe get_user_model should not be executed on module level at all. Consulting django docs it says:

> Generally speaking, you should reference the User model with the AUTH_USER_MODEL setting in code that is executed at import time. get_user_model() only works once Django has imported all models.

**Comment by maxim-kht** [comment]
The logic in serializers involves Django models in order to handle authentication, changing user details, etc. As a result importing django-rest-auth serializers outside of Django context will cause `django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.`. 

>I believe get_user_model should not be executed on module level at all

I tested, and found no difference when get_user_model() is executed on function level.. also Django itself uses the same way of getting user model https://github.com/django/django/blob/b52c73008a9d67e9ddbb841872dc15cdd3d6ee01/django/contrib/auth/forms.py#L22.

Also, not sure if it helps, but the following should run fine:

```
python -c 'import django; django.setup(); from rest_auth.serializers import LoginSerializer'
```
