### ISSUE TITLE
Throttling for registration and login

### ISSUE THREAD

**Issue by aderhgawen** [Tivix/django-rest-auth#274]
Throttle control for registration was recently removed in https://github.com/Tivix/django-rest-auth/commit/83e200e57658b35fa427d2c4ef751d966f1e4a1a. Why has it been removed? Also, there should be throttling for login and password change to prevent brute forcing.

**Comment by maxim-kht** [comment]
@aderhgawen
I explained it in the comment here: https://github.com/Tivix/django-rest-auth/pull/209#issuecomment-254270053. Essentially, adding throttle_scope to rest_auth views will force anybody who is using ScopedRateThrottle to include it for these views in settings - and this might not be straightforward since those views are "hidden" in a third party app.

I think it's better to implement throttling by subclassing RegisterView or LoginView, etc. and adding throttle_scope variable in the subclassed views.

We will add more info related to throttling in our docs.
