### ISSUE TITLE
Password reset email not sending

### ISSUE THREAD

**Issue by cmelone** [Tivix/django-rest-auth#388]
I’m using the default endpoint ‘/rest-auth/password/reset/‘ and posting an email address. But the email never sends, and no error is given in the console or else ware.

It even says “password reset email sent”. I have already determined that it’s not an email backend issue because when I sign up for an account, an email is sent

**Comment by soccer99** [comment]
I'm having the same issue

**Comment by cmelone** [comment]
The weird thing is that it *was* working when I first set it up...I’ll create a new project from scratch and let you know @soccer99

**Comment by soccer99** [comment]
@cmelone  I finally found the issue after following the long trail of imports through the project.

There were three issues on my setup:

One, I didn't have password_reset_email.html, the email template, in my Django python module, nor in my project templates directory.  I added it into my project in templates/registration/

Two, the django.contrib.auth.forms.PasswordResetForm, which is used by rest_auth, filters out users that don't have a password set.  So if you login using a social authentication method, you won't have a password set on your user object and an email won't be sent out.

Three, after solving the first two issues, I finally got an error that was saying I didn't have a url route that resolved 'password_reset_confirm', since I have a spa I had to create a custom route for my project that had the same url parameters as the original `(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})`.

I plan on creating a custom PasswordResetSerializer (original: rest_auth.serializers.PasswordResetSerializer) that doesn't use the Django PasswordResetForm and handle the "passwordless" users another way.

Hope this helps!

**Comment by cmelone** [comment]
@soccer99 I had the template, and made sure that the email was in the system, but I am still not sure why the email isn't being sent. There is  not even an error message. Did you set up the password reset view manually in `views.py`. I'm glad you resolved your issue.

**Comment by maxim25** [comment]
@soccer99 

> Two, the django.contrib.auth.forms.PasswordResetForm, which is used by rest_auth, filters out users that don't have a password set. So if you login using a social authentication method, you won't have a password set on your user object and an email won't be sent out.

Mind sharing how you decided to solve this issue?

**Comment by FlashBanistan** [comment]
@maxim25 While i'm not using the social authentication method, I would imagine it involves calling **user.set_unusable_password()** at some point during or after user creation.
