### ISSUE TITLE
"RelatedObjectDoesNotExist at /rest-auth/user/ User has no userprofile.

### ISSUE THREAD

**Issue by popovvasile** [Tivix/django-rest-auth#411]
I followed exactly the instructions in the documentation about extending the UserProfile. And got the following traceback when trying to login/update
```
Request Method: PUT
Request URL: http://127.0.0.1:8000/rest-auth/user/
Django Version: 2.0.2
Python Executable: /home/kali/Development/EmailAuth/venv/bin/python
Python Version: 3.6.4
Python Path: ['/home/kali/Development/EmailAuth/backend_api', '/home/kali/Development/EmailAuth/venv/lib/python36.zip', '/home/kali/Development/EmailAuth/venv/lib/python3.6', '/home/kali/Development/EmailAuth/venv/lib/python3.6/lib-dynload', '/usr/lib/python3.6', '/home/kali/Development/EmailAuth/venv/lib/python3.6/site-packages']
Server time: Mon, 19 Feb 2018 23:54:38 +0000
```

**Comment by maxim-kht** [comment]
@popovvasile It means that corresponding UserProfile object was not created during the registration. Based on the information provided in the [Stackoverflow question](https://stackoverflow.com/questions/48815250/custom-user-model-in-rest-auth-relatedobjectdoesnotexist/48815717#48815717), it might have happened because signals were not defined on the module level, and as a result UserProfile was not created.

Hence, when trying to update it, it raises error that UserProfile doesn't exist.

**Comment by popovvasile** [comment]
Thank you a lot for the clarification! Would be nice to specify it in the documentation and the change the example on custom UserProfile

**Comment by maxim-kht** [comment]
The example in FAQ shows how to update corresponding UserProfile for User, which was implemented correctly. The issue above was related to definition of Django signals which is outside of scope of django-rest-auth. Related section in Django docs: https://docs.djangoproject.com/en/2.0/topics/signals/
