### ISSUE TITLE
Email Confirmation has wrong url

### ISSUE THREAD

**Issue by acquayefrank** [Tivix/django-rest-auth#48]
Hi, 
I'm currently using django-rest-auth for normal user registration. Problem is every-time a user signups, the email confirmation link has the wrong url.
Eg. User signs up at  www.example.com the email  confirmation url is   www.api.example.com  which should not be so. I'm wondering how I could fix that

**Comment by chachra** [comment]
<http://www.tivix.com/>This is the "Site" model data that causes it. Fix
the url in the db for it, and it should be fixed.

**Comment by acquayefrank** [comment]
Could you kindly clearify that. Should I add the desired url as a Site in my admin??

**Comment by chachra** [comment]
Correct. In your Site model.

**Comment by acquayefrank** [comment]
Thanks for the help

**Comment by mcgeeco** [comment]
Did this really fix your problem? AllAuth seems to take the url from the header of the request instead of the site model, so I can't see how, but maybe I'm missing something.
That is, the AllAuth model's send method calls build_absolute_uri, which uses the request to generate the domain, not the current site. As far as I can see, the only way around this is to set a proxy domain in my nginx settings, which I'd rather not do. Trying to find an easier way, but it's proving really tricky.
[AllAuth Code]
(https://github.com/pennersr/django-allauth/blob/4e81a3c764cbfc26f386f8647c7e2a944e05be2f/allauth/account/models.py#L122)
[Django build_absolute_uri]
(https://docs.djangoproject.com/en/1.8/ref/request-response/#django.http.HttpRequest.build_absolute_uri)
