### ISSUE TITLE
Login with email

### ISSUE THREAD

**Issue by vesterbaek** [Tivix/django-rest-auth#53]
I'm using registration via email. 
```
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True   
ACCOUNT_USERNAME_REQUIRED = False
```
Is there a way to sign in using this or should I write my own Login view? Looks like we currently only support username+password (from `AuthTokenSerializer`)

**Comment by vesterbaek** [comment]
I was missing the allauth authentication backend in settings

```
AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend",
)
````

"email" should be given as "username" to the login endpoint, then it works

**Comment by vesterbaek** [comment]
Should someone want to have users use "email" and "password" fields, one easy way to go about it could look like:

```
import rest_auth.serializers

class LoginSerializer(rest_auth.serializers.LoginSerializer):
	def get_fields(self):
		fields = super(LoginSerializer, self).get_fields()
		fields['email'] = fields['username']
		del fields['username']
		return fields

	def validate(self, attrs):
		attrs['username'] = attrs['email']
		del attrs['email']
		return super(LoginSerializer, self).validate(attrs)
```

**Comment by philippeluickx** [comment]
+1 in having a graceful implementation on this.
Would be good to check allauth presets (if present) and have it implemented.

**Comment by cmdelatorre** [comment]
This is exactly what I needed. It'd be great to have it as a feature or at least mentioned in the documentation.

**Comment by geekodour** [comment]
where to put in the serializer?

**Comment by changalberto** [comment]
I'm having trouble getting the rest api to accept an email as `username`. Is this still relevant with version `0.9.1`?

**Comment by MichaelWashburnJr** [comment]
This worked for me without the serializer and just adding the settings. Here are my versions:
```
        'Django==1.11.7',
        'django-allauth==0.34.0',
        'django-rest-auth==0.9.2',
        'djangorestframework==3.7.3',
```

**Comment by pravin-d** [comment]
Hey Guys.. Newbie alert. 
Wrapping my head around all the stuff that happens under the hood in django is a difficult task for. Put in the mix of rest_auth, allauth and drf and regular forms and it just blows my mind off.
A simple thing like email login should work. But it does not. Lots of suggestions on authentication backends, etc, etc.

After doing some debugging into the core I figured that rest_auth calls django's auth method. Django's auth always authenticates with respect to username field.
A Custom User model and/or manager should solve the problem I guess. Need to check how to do it.

A little bit of documentation with example on how to use social auth with pre-conditions and list of gotchas that others frequently face due to rest_auth integration with third_party libs would really go long way for beginners like me.

**Comment by tagnev** [comment]
Hi,

I'm using registration via email but I am not sure why in the API END POINT its showing "USERNAME" as well.  Below are the settings,
`ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False`

How can we disable the USERNAME option from the front end API
