### ISSUE TITLE
KeyError on invalid access tokens for Social Authentication ( Google and LinkedIn)

### ISSUE THREAD

**Issue by rohitvarkey** [Tivix/django-rest-auth#61]
I tried to implement REST based social authentication for Google and LinkedIn (Oauth2) like the Facebook example shown in the documentation. 

It works fine for valid access tokens but on entering invalid access tokens, it raises a KeyError for 'id' rather than the neat 400 BAD REQUEST response on invalid tokens for the Facebook example.

**Comment by ahawad** [comment]
I have the same issues with Google authentication

**Comment by lukeburden** [comment]
This happens due to a lack of error handling in allauth. I've created an issue here, you could support it or describe your experience there if you like.

https://github.com/pennersr/django-allauth/issues/985

Once errors are handled properly there and fed back up to django-rest-auth, better support for it could be added to the login views here.

**Comment by lukeburden** [comment]
This has been fixed for Google in https://github.com/pennersr/django-allauth/commit/8705514dc164577f801cdacb5c46623c8cb9909b. Check if it's still an issue for LinkedIn and if not, I'd suggest closing this issue.

**Comment by mariodev** [comment]
No response. Closing.

**Comment by mav-erick** [comment]
The issue still exists for LinkedIn.
